#!/usr/local/bin/node

//Returns the paragraph from Wiki link, stripped of reference numbers

let request = require('request');
let url = process.argv[2];


if (!url) {
  console.log('Please enter a valid URL. Usage: ./wikp <url>');
  process.exit(1);
}

const jsdom = require('jsdom');
const { JSDOM } = jsdom;

request(url, function(error, response, body) {
  //stimulate a DOM
  let { document } = (new JSDOM(body)).window;

  //grab all paragraphs and references
  let paragraphs = document.querySelectorAll('p');
  let references = document.querySelectorAll('.reference');

  //remove references
  references.forEach(function(reference) {
    reference.remove();
  });

  //print paragraphs
  paragraphs.forEach(function(paragraph) {
    console.log(paragraph.textContent);
  });
});
